# Generated by Django 5.1 on 2025-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("none", "—"),
                    ("active", "Триває"),
                    ("pause", "Пауза"),
                    ("done", "Завершено"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
