# Generated by Django 5.1 on 2025-09-03 17:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_dealattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealattachment",
            name="file",
            field=models.FileField(
                upload_to=main.models.deal_upload_path,
                validators=[main.models.validate_attachment],
            ),
        ),
    ]
