# Generated by Django 5.2.5 on 2025-09-05 02:34

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_dealattachment_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="employee",
            name="absences_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_place",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employee",
            name="contract_file",
            field=models.FileField(
                blank=True, null=True, upload_to=main.models.employee_upload_path
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("m", "Чоловіча"), ("f", "Жіноча"), ("x", "Інше/Не вказано")],
                default="x",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Вільний/вільна"),
                    ("married", "Одружений/заміжня"),
                    ("divorced", "Розлучений/розлучена"),
                    ("widowed", "Вдівець/вдова"),
                ],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=main.models.employee_upload_path
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="registration_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
