# Generated by Django 5.1 on 2025-09-10 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_employee_options_employee_absences_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Deal_Order",
                "verbose_name_plural": "Deal_Orders",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="main_client_name_c070b5_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["phone"], name="main_client_phone_6bdf93_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="main_client_email_7021a2_idx"),
        ),
    ]
