# Generated by Django 5.1 on 2025-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0002_booking_allow_unskilled_booking_status_and_more"),
        ("main", "0009_employee_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                to="beauty.service",
                verbose_name="Навички (послуги)",
            ),
        ),
    ]
