# Generated by Django 5.1 on 2025-09-10 08:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0007_alter_employee_options_employee_absences_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Ресурс")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурси",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=160, verbose_name="Назва"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Код/артикул"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Базова ціна",
                    ),
                ),
                (
                    "duration_min",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Тривалість, хв"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Послуга",
                "verbose_name_plural": "Послуги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DealLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="К-сть",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна за од."
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сума"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="main.deal",
                        verbose_name="Угода",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_lines",
                        to="beauty.service",
                        verbose_name="Послуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рядок угоди",
                "verbose_name_plural": "Рядки угоди",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(db_index=True, verbose_name="Початок"),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Кінець"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#88CCEE", max_length=7, verbose_name="Колір"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Нотатка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="main.deal",
                        verbose_name="Угода",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="main.employee",
                        verbose_name="Майстер",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beauty.resource",
                        verbose_name="Ресурс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запис",
                "verbose_name_plural": "Записи",
                "indexes": [
                    models.Index(
                        fields=["start_at"], name="beauty_book_start_a_a36b41_idx"
                    ),
                    models.Index(
                        fields=["end_at"], name="beauty_book_end_at_9da353_idx"
                    ),
                ],
            },
        ),
    ]
