# Generated by Django 5.1 on 2025-09-16 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0001_initial"),
        ("main", "0008_alter_deal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="allow_unskilled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("tentative", "Попередній"),
                    ("confirmed", "Підтверджено"),
                    ("cancelled", "Скасовано"),
                ],
                default="confirmed",
                max_length=16,
                verbose_name="Статус бронювання",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="main.employee",
                verbose_name="Майстер",
            ),
        ),
    ]
