# Generated by Django 5.1 on 2025-09-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0002_booking_allow_unskilled_booking_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="allow_unskilled",
            field=models.BooleanField(
                default=False, verbose_name="Призначено без навички"
            ),
        ),
    ]
