# Generated by Django 5.1 on 2025-09-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0003_alter_booking_allow_unskilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="group",
            field=models.CharField(
                choices=[
                    ("hair", "Перукар"),
                    ("nails", "Манікюр/Педикюр"),
                    ("cosmet", "Косметологія"),
                    ("barber", "Барбер"),
                ],
                default="hair",
                max_length=12,
                verbose_name="Група",
            ),
        ),
    ]
